language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - npm install
  - ng build
  - mkdir build-artifact
  - zip -r build-artifact/ng-harvest-jira-sync.zip dist/*

deploy:
  provider: s3
  access_key_id: "AKIAW24IA3X4K5DIW46H"
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: "ng-harvest-jira-sync-travis-ci"
  skip_cleanup: true
  local_dir: build-artifact
  on:
    branch: feature/travis-ci
