language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - npm install
  - ng build
  - zip -r ng-harvest-jira-sync.zip dist/*

addons:
  artifacts:
    paths:
      - ng-harvest-jira-sync.zip
